[project]
name = "salesiq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.1",
    "django-anymail[resend]>=15.1",
    "django-extensions>=4.1",
    "django-vite>=3.1.0",
    "email-validator>=2.3.0",
    "mysqlclient>=2.2.8",
    "nanoid>=2.0.0",
    "pydantic>=2.13.4",
    "pymysql>=1.2.0",
    "python-decouple>=3.8",
    "uuid6>=2025.0.1",
]
