"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from core.url_names import ACCOUNTS
from pathlib import Path
from decouple import config
from typing import cast
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENVIRONMENT = config("ENV", default="local")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY") or "django-insecure-g-#*5w34-8=wbi_n0z$qaw60%33sc&aav^1+s^b0!0p-1z!b(k"
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_DOMAINS = cast(str, config("ALLOWED_DOMAINS", default="")).split(", ")
ALLOWED_HOSTS = ALLOWED_DOMAINS or []

LOGIN_URL = ACCOUNTS.AUTH.LOGIN
LOGOUT_REDIRECT_URL = ACCOUNTS.AUTH.LOGIN
LOGIN_REDIRECT_URL = ACCOUNTS.DASHBOARD


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    "django_extensions",
    "django_vite",
    "anymail",
    
    "accounts.apps.AccountsConfig",
    "customers.apps.CustomersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    "middlewares.enforce_onboarding.OnboardingEnforcementMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.url_name_registry",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if ENVIRONMENT == "local":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": "3306",
        "CONN_MAX_AGE": 120,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "connect_timeout": 10,
            "read_timeout": 30,
            "write_timeout": 30,
            "isolation_level": "read committed",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATICFILES_DIRS = [BASE_DIR / "static"]

match ENVIRONMENT:
    case "local":
        STATIC_ROOT = BASE_DIR / "staticfiles"
        MEDIA_ROOT = BASE_DIR / "mediafiles"
        
    case "prod":
        DOCUMENT_ROOT = Path(
            cast(str, config("DOCUMENT_ROOT", default=(BASE_DIR)))
        )
        STATIC_ROOT = DOCUMENT_ROOT / "static"
        MEDIA_ROOT = DOCUMENT_ROOT / "media"
        
    case _:
        pass


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {
            "host": config("SMTP_HOST", default="salesiq.com.ng"),
            "port": config("SMTP_PORT", default=465, cast=int),
            "username": config("SMTP_USER", default=""),
            "password": config("SMTP_PASSWORD", default=""),
            "use_ssl": True,
        },
    },
    "anymail": {
        "BACKEND": "anymail.backends.resend.EmailBackend",
        "OPTIONS": {
            "api_key": config("RESEND_API_KEY"),
        },
    },
}
MAILER_EMS = "anymail"
ANYMAIL = {
    "REQUESTS_TIMEOUT": (5, 10),
}

DEFAULT_FROM_EMAIL = "SalesIQ <no-reply@notifications.salesiq.com.ng>"


DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        # "static_url_prefix": "dist", # enable to build prod dist
        "manifest_path": BASE_DIR / "static" / "dist" / "manifest.json",
        # "dev_server": {
        #     "name": "vite",
        #     "url": "http://localhost:5173",
        # },
        # "build_dir": BASE_DIR / "app/static/dist",
        # "static_url": "/static/dist/",
    }
}

if not DEBUG:
    DJANGO_VITE["default"]["static_url_prefix"] = "dist"
    
AUTH_USER_MODEL = "accounts.CustomUserModel"
